import Head from 'next/head';
import { Inter } from 'next/font/google';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
    AiFillGithub,
    AiFillLinkedin,
    AifillYoutube,
} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import avatar from '../public/avatar.jpeg';
import design from '../public/design.png';
import code from '../public/code.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';
import { TypeAnimation } from 'react-type-animation';
import { MotionConfig } from 'framer-motion';
import { motion } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {

    const [darkMode, setDarkMode] = useState(true);

    return (
        <div className={darkMode ? "dark" : ""}>
            {/* Header */}
            <Head>
                <title>Ryan He Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
                {/* Section 1 */}
                <section className="min-h-screen">
                    {/* Nav bar */}
                    <nav className="py-10 mb-12 flex justify-between dark:text-white">
                        <h1 className="font-burtons text-xl animate-bounce">Ryan He</h1>
                        <ul className="flex items-center">
                            <li>
                                <motion.div whileInView={{ opacity: 1 }} whileHover={{ scale: 1.1 }} transition={{ duration: 0.5, type: 'tween' }}>
                                    <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
                                </motion.div>
                            </li>
                            <li>
                                <motion.div whileInView={{ opacity: 1 }} whileHover={{ scale: 1.1 }} transition={{ duration: 0.5, type: 'tween' }}>
                                    <a
                                        className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                                        href="#"
                                    >
                                        Resume
                                    </a>
                                </motion.div>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center p-10">
                        <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Hi! My name is Ryan He,</h2>
                        {/* <h3 className="text-2xl py-2 dark:text-white md:text-3xl">Computer Science Major</h3> */}
                        <TypeAnimation
                            sequence={[
                                'I am a Computer Science Major ',
                                2000,
                                'I am a problem solver ',
                                2000,
                                'I am a lifelong learner ',
                                2000
                            ]}
                            wrapper="span"
                            cursor={true} // Display a blnking cursor after the typed text
                            repeat={Infinity}
                            className='text-2xl py-2 dark:text-white md:text-3xl'
                        />
                        <p className="text-md py-8 leading-8 text-gray-800 md:text-xl max-w-2xl mx-auto dark:text-gray-200">
                            I'm a CS undergrad at SFU with an interest in full-stack development. <br />
                            I love diving into new technologies to broaden my knowledge and develop new skills to ovecome real-world challenges.

                        </p>
                        <p className="text-md leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
                            Open to any interesting opportunities!
                        </p>
                    </div>

                    {/* Icons */}
                    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                        <motion.div whileInView={{ opacity: 1 }} whileHover={{ scale: 1.1 }} transition={{ duration: 0.5, type: 'tween' }}>
                            <a href='https://www.linkedin.com/in/ryanhjs/' target="_blank">
                                <AiFillLinkedin className='cursor-pointer hover:bg-cyan-300 rounded-full' />
                            </a>
                        </motion.div>
                        <motion.div whileInView={{ opacity: 1 }} whileHover={{ scale: 1.1 }} transition={{ duration: 0.5, type: 'tween' }}>
                            <a href='https://github.com/RyanHJS/' target="_blank">
                                <AiFillGithub className='cursor-pointer hover:bg-cyan-300 rounded-full' />
                            </a>
                        </motion.div>
                    </div>

                    {/* 3D Image */}
                    <div>

                        <motion.div whileInView={{ opacity: 1 }} whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }} transition={{ duration: 0.1, type: 'tween' }}>
                            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-25 md:w-25">
                                <Image src={avatar} layout="fill" objectiveFit="cover" />
                            </div>
                        </motion.div>
                    </div>
                </section>

                {/* Section 2 */}
                <section>
                    {/* My work Experience */}
                    <div >
                        <h3 className='text-3xl font-medium pt-8 pb-2 dark:text-white'>My Work Experience</h3>
                        <h4 className='text-md pt-10 pb-2 leading-8 tet-gray-80 dark:text-gray-200 '>
                            SAP - Software Logistics Engineer (September 2021- May 2022)</h4>
                        <p className="text-md py-2 leading-8 text-gray-800 max-w-3xl dark:text-gray-200">I worked as a SAP iXp intern on the BTP Core Platform Services
                            team where I conducted system analysis, testing, and <span className='text-teal-500'>debugging</span>.
                            I also examined resource consumption in physical and <span className='text-teal-500'>virtual environments </span>
                            (VMware, PowerVM, etc) and optimized resource usage and response times.</p>
                        <p className="text-md py-2 leading-8 text-gray-800 max-w-3xl dark:text-gray-200">I am honoured to have been nominated by my manager to
                            join <span className='text-teal-500'>Fast Track</span> -  an initiative of SAP Internship Experience Program,
                            for success, high motivation and commitment during internship/working student time.</p>
                    </div>
                    {/* Portofolio */}
                    <div>
                        <h3 className='text-3xl  font-medium pt-8 pb-2 dark:text-white'>My Projects</h3>
                        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                            <div className="basis-1/3 flex-1 ">
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={web1}
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={web2}
                                />
                            </div>
                        </div>
                    </div>

                </section>

                {/* Footer */}
                <section>
                    <div className='pt-20'>
                        <p className="font-burtons text-xs text-center dark:text-gray-200">@2023 Ryan He</p>
                        <p className="font-burtons text-xs text-center dark:text-gray-200">With Inspiration From developedbyed</p>
                    </div>
                </section>
            </main>
        </div >
    );
}