import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import avatar from '../../public/static/avatar.jpeg';
import web1 from '../../public/static/web1.png';
import web2 from '../../public/static/web2.png';
import favicon from '../../public/static/favicon.ico';
import { useState } from 'react';

import Navbar from './Components/Navbar';
import About from './Components/About';
import Work from './Components/Work';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {

    const [darkMode, setDarkMode] = useState(true);

    return (
        <div className={darkMode ? "dark" : ""}>
            {/* Header */}
            <Head>
                <title>Ryan He Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />

                <link rel="shortcut icon" href="/static/favicon.ico" />
                <link rel="apple-touch-icon" sizes="180x180" href="/static/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon-16x16.png" />
            </Head>

            <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">

                {/* Section 1 */}
                <section className="min-h-screen">
                    {/* Nav bar */}
                    <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
                    {/* About me */}
                    <About Image={Image} avatar={avatar} />
                </section>

                {/* Section 2 */}
                <section>
                    {/* My work Experience */}
                    <Work />
                    {/* Portofolio */}
                    <div>
                        <h3 className='text-3xl  font-medium pt-8 pb-2 dark:text-white'>My Projects</h3>
                        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                            <div className="basis-1/3 flex-1 ">
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={web1}
                                />
                            </div>
                            <div className="basis-1/3 flex-1">
                                <Image
                                    className="rounded-lg object-cover"
                                    width={"100%"}
                                    height={"100%"}
                                    layout="responsive"
                                    src={web2}
                                />
                            </div>
                        </div>
                    </div>

                </section>

                {/* Footer */}
                <section>
                    <div className='pt-20'>
                        <p className="font-burtons text-xs text-center dark:text-gray-200">@2023 Ryan He</p>
                        <p className="font-burtons text-xs text-center dark:text-gray-200">With Inspiration From developedbyed</p>
                    </div>
                </section>
            </main>
        </div >
    );
}